 计算机视觉（24春）作业1-4 (25分)
---

## 题目: DLT算法的使用
- **给定理想二维匹配点对集合，请使用DLT算法估计其所对应的单应性矩阵H。**
- 二维匹配点数据文件名为：2D_correspondences4DLT_H.txt
    - 存储格式为：每行4个数，分别为 (x1, y1, x2, y2)，表示两个平面间的匹配点坐标。
- 请在下面的代码框中编写DLT算法的实现，并输出估计得到的单应性矩阵H。

---
### 环境配置：以anaconda为例

```shell
    # anaconda的安装请根据自己的操作系统下载对应的安装包，官网链接：https://www.anaconda.com/products/distribution
    # 具体安装过程可以参考知乎，b站，CSDN等网站上的安装教程
    # 假设你已经成功安装了anaconda，打开terminal（linux/mac）or Anaconda Prompt（windows）
    cd <你的文件夹路径>
    conda create -n cv python=3.8 # 创建python虚拟环境，名字为cv，python版本为3.8
    conda activate cv # 激活虚拟环境
    conda install jupyter notebook # 安装jupyter notebook
    pip install --upgrade pip # 升级pip
    pip install opencv-python # 安装opencv
    pip install numpy # 安装numpy
    jupyter notebook # 运行jupyter notebook
    # 上一条指令将在默认的网页浏览器中开启一个新的工作空间，你可以在其中打开该.ipynb文件
```

---

## 数据读取与展示部分
- 请在下面的代码框中实现对数据的读取与展示。
- 评分细则：
    1.数据读取与展示的正确性。（5分）

In [1]:
# Code here

# hint: use np.loadtxt

import numpy as np

data_path = "2D_correspondences4DLT_H.txt"

raw_data = np.loadtxt(data_path)

print(raw_data)

data_pairs = []

for pair in raw_data:
    data_pairs.append([[pair[0], pair[1]], [pair[2], pair[3]]])
    
print(data_pairs)

[[54.88135039 71.51893664  0.68667351  3.72021807]
 [60.27633761 54.4883183   0.79776499  3.60792972]
 [42.36547993 64.58941131  0.64428247  3.76152253]
 [43.75872113 89.17730008  0.57349348  3.83416893]
 [96.36627605 38.34415188  1.07993083  3.32594529]
 [79.17250381 52.88949198  0.89884038  3.50755548]
 [56.80445611 92.55966383  0.62655524  3.781624  ]
 [ 7.10360582  8.71292997  0.71414076  3.64447226]
 [ 2.02183974 83.26198455  0.31403196  4.09162811]
 [77.81567509 87.00121482  0.73101596  3.67739109]]
[[[54.88135039273247, 71.51893663724195], [0.6866735123515855, 3.720218074625621]], [[60.276337607164386, 54.48831829968969], [0.7977649932521848, 3.6079297186517345]], [[42.36547993389047, 64.58941130666561], [0.644282469091861, 3.7615225341500578]], [[43.75872112626925, 89.17730007820798], [0.5734934788866926, 3.834168934491985]], [[96.36627605010293, 38.34415188257777], [1.0799308264121767, 3.3259452850839932]], [[79.17250380826646, 52.88949197529045], [0.8988403820408728, 3.507555

---

## 数据处理部分
- 请在下面的代码框中实现数据的预处理，主要为齐次坐标的构造，并展示你的处理结果。
- 评分细则：
    1. 齐次坐标构造是否正确（5分）

In [2]:
# Code here

for pair in data_pairs:
    # print(pair)
    pair[0].append(1)
    pair[1].append(1)
    
print(data_pairs) # 10 pairs

[[[54.88135039273247, 71.51893663724195, 1], [0.6866735123515855, 3.720218074625621, 1]], [[60.276337607164386, 54.48831829968969, 1], [0.7977649932521848, 3.6079297186517345, 1]], [[42.36547993389047, 64.58941130666561, 1], [0.644282469091861, 3.7615225341500578, 1]], [[43.75872112626925, 89.17730007820798, 1], [0.5734934788866926, 3.834168934491985, 1]], [[96.36627605010293, 38.34415188257777, 1], [1.0799308264121767, 3.3259452850839932, 1]], [[79.17250380826646, 52.88949197529045, 1], [0.8988403820408728, 3.507555484122706, 1]], [[56.80445610939323, 92.5596638292661, 1], [0.6265552397623269, 3.7816240045336915, 1]], [[7.103605819788694, 8.712929970154072, 1], [0.7141407606494478, 3.6444722597213075, 1]], [[2.021839744032572, 83.2619845547938, 1], [0.31403196429432656, 4.091628106753371, 1]], [[77.81567509498505, 87.00121482468191, 1], [0.7310159589293976, 3.677391087190065, 1]]]


--- 

## DLT算法实现部分
- 请在下面的代码框中实现DLT算法，并输出估计得到的单应性矩阵H。
- 注意：
    1. 你可以直接使用cv2.findHomography()函数，如果采用此方法，请在下面的Markdown框中附上手算的过程和结果，并对比两种方法的结果。
        - 评分细则：
            - opencv函数调用是否正确（5分）
    2. 你也可以自己实现DLT算法，此时则**不需要**附上手算的过程和结果。
        - 评分细则：
            - DLT算法实现是否正确（10分）
            - 结果是否正确（5分）

In [3]:
# Code here

# try to implement DLT

# Step1: Calculate A_i Matrix (2 * 9) for each point

A_list = []
for itemp in data_pairs:
    x_i = np.array(itemp[0])
    x_i_s = itemp[1][0]
    y_i_s = itemp[1][1]
    w_i_s = itemp[1][2]

    A = np.block(
        [
            [np.zeros(3), -w_i_s * x_i, y_i_s * x_i],
            [w_i_s * x_i, np.zeros(3), -x_i_s * x_i],
        ]
    )

    A_list.append(A)

# Step2: Assemble A Matrix into (2n * 9)

A_assembled = np.vstack(A_list)


# Step3: Obtain the SVD of A, the unit singular vector correspponding to the smallest singular value is the solution

U, D, V = np.linalg.svd(A_assembled) # D is the list of diagonal values, descending order

# Step4: Extract the solution from V

h = V[-1, :]
H = h.reshape(3, 3)
H = H / H[2,2]
print(H)



[[1.707 0.586 1.   ]
 [2.707 8.242 2.   ]
 [1.    2.    1.   ]]


In [4]:

# Compare the results with opencv build-in function cv2.findHomography()

import cv2

src_pts = np.array([itemp[0:2] for itemp in raw_data])

dst_pts = np.array([itemp[2:4] for itemp in raw_data])

H_cv2, _ = cv2.findHomography(src_pts, dst_pts)

print(H_cv2) # the results only match up to a scale factor (\approx -10), which is acceptable

# 结果在误差范围内一致

[[1.7067319  0.58590676 0.9999535 ]
 [2.70657362 8.24069996 2.00026096]
 [0.99984264 1.99968433 1.        ]]


---
*如果直接调用cv2.findHomography()函数，请在此处附上手算的过程和结果：*
- 如有需要，请熟悉Latex和Markdown的相关语法，方便书写数学公式和文字说明。
- 评分细则：
    - 算法流程正确性（4分）
    - SVD分解结果正确性（4分）
    - 两种方法结果一致性（2分）
- 以下为答题区域，可以使用多个Markdown或者Code单元格

---